"""Portable offline report: no CDN, fetch, Python server or external scripts."""
import json


def render(report,path):
    template='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Bayesian context review</title><style>
body{font:15px system-ui;background:#f5f5ef;color:#22382f;margin:0;padding:30px}main{max-width:1250px;margin:auto}h1{font-size:36px;margin-bottom:8px}p{line-height:1.6}.note{background:#fff1c9;padding:18px;border-radius:12px}.stats{display:flex;gap:12px;flex-wrap:wrap;margin:20px 0}.stat,section{background:white;padding:20px;border-radius:14px;border:1px solid #dedfd5}.stat b{font-size:26px;display:block}section{margin:18px 0}input,select{font:inherit;padding:10px;border:1px solid #bbc9bf;border-radius:7px}table{width:100%;border-collapse:collapse}th,td{text-align:left;border-bottom:1px solid #e4e8e1;padding:10px;vertical-align:top}button{font:inherit;border:0;background:#e6eee5;padding:7px 13px;border-radius:7px;cursor:pointer}tr.selected{background:#fff1c9}.approve{color:#1d7044}.step_up{color:#a35808}.decline{color:#a62626}.small{font-size:12px;color:#55695b;overflow-wrap:anywhere}.graph{display:flex;align-items:center;gap:18px;flex-wrap:wrap}.node{padding:12px 20px;background:#f2e5ba;border:1px solid #decc88;border-radius:9px}.latent{background:#e9edf8;border-color:#b7c4e2}#source{max-height:140px;overflow:auto}.scroll{overflow:auto;max-height:380px}#detail{scroll-margin-top:20px}svg{width:100%;height:180px}footer{font-size:13px;color:#55695b;margin-top:24px}
</style><main><p>AGENT ON LEASH / OFFLINE PROTOTYPE</p><h1>Bayesian context review</h1>
<p>Explore contextual novelty and posterior influence, with the original outcome kept separate.</p>
<div class="note"><b>Synthetic temporal replay · Expert assumptions</b><br>This is not fraud probability or the actual reason an issuer declined a transaction. Historical knowledge timestamps and source coverage are assumed. The sensitivity range is not a confidence interval.</div>
<div class="stats" id="stats"></div><section><h2>Network structure</h2><div class="graph"><div class="node">Merchant novelty<br>↓ Country novelty<br>↓ Device novelty<br>↘ Amount atypicality</div><span>→</span><div class="node latent">Device + country + velocity<br>↓ Session anomaly</div><span>→</span><div class="node latent">Merchant + amount + session<br>↓ Context anomaly</div><span>→</span><div class="node">Approve / step up<br>Hard rules remain authoritative</div></div><p class="small">Country and device novelty share dependent CPTs. The diagram groups parents; the committed configuration defines every directed edge.</p></section>
<section><h2>Transactions</h2><input id="search" placeholder="Search TR03359, card or merchant" aria-label="Search"><select id="filter" aria-label="Recommendation"><option value="">All recommendations</option><option>approve</option><option>step_up</option><option>decline</option></select><span id="count" class="small"></span><div class="scroll"><table><thead><tr><th>Transaction</th><th>Card → merchant</th><th>Recorded outcome</th><th>Recommendation</th><th>Posterior</th><th></th></tr></thead><tbody id="list"></tbody></table></div><p class="small">Showing up to 100 matches. Search an ID to drill into any replayed purchase.</p></section>
<section id="detail"><h2>Select a transaction</h2></section><section><h2>Replay verification</h2><pre id="checks" style="white-space:pre-wrap"></pre></section><footer>Full immutable receipts are stored locally in the receipts database named in the replay verification. report.json contains the portable explanations. No live payments are authorized.</footer></main>
<script id="data" type="application/json">__DATA__</script><script>
const report=JSON.parse(document.getElementById('data').textContent),rows=report.rows,s=report.summary;
const esc=x=>String(x??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pct=x=>x==null?'—':(100*x).toFixed(2)+'%';
document.getElementById('stats').innerHTML=[['Historical purchases',s.historical_purchase_count],['Model evaluated',s.modeled_count],['Sensitivity changes',s.sensitivity_changes],['Temporal violations',s.temporal_violations]].map(([k,v])=>`<div class="stat"><b>${v}</b>${k}</div>`).join('');
document.getElementById('checks').textContent=JSON.stringify(s,null,2);
function list(){const q=document.getElementById('search').value.toLowerCase(),f=document.getElementById('filter').value;const matches=rows.filter(r=>(!f||r.decision===f)&&[r.id,r.card,r.merchant,r.run].join(' ').toLowerCase().includes(q));document.getElementById('count').textContent=' '+matches.length+' matches';document.getElementById('list').innerHTML=matches.slice(0,100).map(r=>`<tr><td>${esc(r.id)}<br><small>${esc(r.time)}</small></td><td>${esc(r.card)} → ${esc(r.merchant)}</td><td>${esc(r.original_outcome)}</td><td class="${r.decision}">${esc(r.decision)}</td><td>${pct(r.analysis?.baseline)}</td><td><button data-id="${esc(r.id)}">Inspect</button></td></tr>`).join('');}
function detail(id){const r=rows.find(r=>r.id===id),a=r.analysis;document.getElementById('detail').innerHTML=`<h2>${esc(r.card)} → ${esc(r.merchant)} → ${esc(r.id)}</h2><p><b class="${r.decision}">${esc(r.decision)}</b> · ${esc(r.reason)}<br>Recorded outcome: ${esc(r.original_outcome)}. ${r.run==='historical'?'Analytical eligibility assumed.':'Scenario: '+esc(r.run)}</p>${a?`<p>Context-anomaly posterior: <b>${pct(a.baseline)}</b> · Parameter sensitivity: ${pct(a.minimum)}–${pct(a.maximum)}<br>Recommendation changes across scenarios: ${a.recommendation_changes?'Yes':'No'}</p>`:'<p>Model not evaluated: rule gate or required evidence prevented inference.</p>'}<table><thead><tr><th>Feature</th><th>Value / state</th><th>History</th><th>Without feature</th><th>Influence</th></tr></thead><tbody>${Object.entries(r.features).map(([k,v])=>{const i=a?.influence.find(x=>x.feature===k);return `<tr><td>${esc(k)}</td><td>${v.value===1?'Novel / atypical':v.value===0?'Familiar / ordinary':'Not observed'}<br><small>${esc(v.state)}</small></td><td>${v.sample_size} approved purchases<br>${v.coverage_days.toFixed(1)} days</td><td>${pct(i?.without_feature)}</td><td>${i?(i.delta>=0?'+':'')+(100*i.delta).toFixed(2)+' percentage points<br>'+esc(i.interpretation):'Marginalized or model not run'}</td></tr>`}).join('')}</tbody></table><p class="small">Influence removes one observation and marginalizes it. Deltas overlap and are not causal contributions. None identifies the original decline reason.</p><h3>Eligible supporting transactions</h3><div id="source">${r.sources.map(esc).join(', ')||'None'}</div><p class="small">Paths: card ← ON_CARD ← historical authorization → AT_MERCHANT → merchant. Source versions, timestamps and hashes are in the complete receipt.<br>Snapshot: ${esc(r.snapshot_id)}<br>Receipt: ${esc(r.receipt_hash)}</p>`;}
document.getElementById('search').addEventListener('input',list);document.getElementById('filter').addEventListener('change',list);document.getElementById('list').addEventListener('click',e=>{if(e.target.dataset.id){detail(e.target.dataset.id);document.getElementById('detail').scrollIntoView({behavior:'smooth'});}});list();detail(rows.find(r=>r.id==='TR03359')?.id||rows[0].id);
</script></html>'''
    data=json.dumps(report,separators=(',',':'),allow_nan=False).replace('<','\\u003c')
    path.write_text(template.replace('__DATA__',data))
