"""Self-contained, offline viewer; all source text is inserted with textContent."""
import json


def render_viewer(results, output):
    payload = json.dumps(results).replace('<', '\\u003c').replace('>', '\\u003e').replace('&', '\\u0026')
    template = '''<!doctype html>
<html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Knowledge graph • Evidence review</title>
<style>
:root{font-family:system-ui,sans-serif;color:#183129;background:#f3f5ef}body{margin:0}main{max-width:1180px;margin:auto;padding:40px 24px}h1{font-size:36px;letter-spacing:-1px;margin:10px 0}h2{font-size:20px}p{line-height:1.5}.eyebrow{font-size:12px;text-transform:uppercase;letter-spacing:2px;color:#587263}.muted{color:#587263}select{font:inherit;padding:12px;border:1px solid #b9c6bd;border-radius:8px;background:white;max-width:100%}.controls{display:flex;gap:24px;flex-wrap:wrap;margin:24px 0}.controls label{display:flex;flex-direction:column;gap:8px;flex:1;min-width:220px}.panel{background:#fff;border:1px solid #dce3d8;border-radius:14px;padding:24px;margin:18px 0}#decision{font-size:25px;font-weight:650}#graph{width:100%;min-height:220px}table{border-collapse:collapse;width:100%;font-size:14px}td,th{text-align:left;padding:10px;border-bottom:1px solid #e3e8df;vertical-align:top;overflow-wrap:anywhere}th{color:#587263;font-weight:500}.badge{padding:5px 10px;border-radius:20px;background:#e8eee6;font-size:12px}.scroll{overflow:auto}code{overflow-wrap:anywhere}.note{font-size:13px;color:#587263}
</style><main><div class="eyebrow">Agent on a Leash / SCEN0001</div><h1>Follow the evidence.</h1><p class="muted">Ten requests. Traceable decisions. Select a request and inspect its source-record paths.</p>
<p class="note">Synthetic fixtures · Simulation policy · Explanation contributions are not proven fraud causes</p>
<div class="controls"><label>Purchase request<select id="request"></select></label><label>Evidence path<select id="path"></select></label></div>
<section class="panel"><span class="badge">Simulation decision</span><p id="decision"></p><p id="cause"></p><p id="state" class="muted"></p></section>
<section class="panel"><h2>Highlighted evidence path</h2><p id="reason"></p><div class="scroll"><svg id="graph" role="img" aria-label="Source-record evidence path"></svg></div><p class="note">Arrows show the stored relationship direction. Labels and the source table carry the meaning as well as colour.</p></section>
<section class="panel"><h2>Source provenance</h2><div class="scroll"><table><thead><tr><th>Relationship</th><th>Source file</th><th>Source record</th><th>Source fields</th></tr></thead><tbody id="provenance"></tbody></table></div></section>
<section class="panel"><h2>Checks and explanation contributions</h2><div class="scroll"><table><thead><tr><th>Check</th><th>Result</th><th>Expected</th><th>Observed</th><th>Contribution</th></tr></thead><tbody id="checks"></tbody></table></div><p class="note">Monetary values are integer cents. Hard-rule failures jointly determine 100% of a decline decision.</p></section>
</main><script id="data" type="application/json">__PAYLOAD__</script><script>
const results=JSON.parse(document.getElementById('data').textContent), $=id=>document.getElementById(id), ns='http://www.w3.org/2000/svg';
function text(el,value){el.textContent=value}
function option(el,value,label){const o=document.createElement('option');o.value=value;o.textContent=label;el.append(o)}
function row(el,values){const tr=document.createElement('tr');for(const v of values){const td=document.createElement('td');td.textContent=typeof v==='string'?v:JSON.stringify(v);tr.append(td)}el.append(tr)}
function svg(tag,attrs,value){const el=document.createElementNS(ns,tag);for(const [k,v] of Object.entries(attrs))el.setAttribute(k,v);if(value!==undefined)el.textContent=value;return el}
results.forEach((r,i)=>option($('request'),i,`${r.input.authorization_id} · CHF ${(r.input.billing_amount_chf/100).toFixed(2)} · ${r.KG_Rootcause.decision}`));
function showRequest(){const r=results[+$('request').value],e=r.KG_Rootcause;text($('decision'),e.decision.replace('_',' ').toUpperCase());text($('cause'),e.decision_cause.rules.join(' · '));const spend=s=>s.events.filter(x=>x.status==='approved').reduce((a,x)=>a+x.billing_amount_chf,0);text($('state'),`Run approvals: CHF ${(spend(r.state_before)/100).toFixed(2)} → CHF ${(spend(r.state_after)/100).toFixed(2)}. Context cutoff: ${r.dynamic_context.as_of} (exclusive).`);$('path').replaceChildren();e.root_cause_paths.forEach((p,i)=>option($('path'),i,`${p.reason_code} → ${p.nodes[p.nodes.length-1]}`));$('checks').replaceChildren();[...e.supporting_evidence,...e.counter_evidence].forEach(c=>row($('checks'),[c.reason_code,c.status,c.expected,c.observed,`${c.evidence_contribution_percent}%`]));showPath()}
function showPath(){const e=results[+$('request').value].KG_Rootcause,p=e.root_cause_paths[+$('path').value],g=$('graph');g.replaceChildren();$('provenance').replaceChildren();text($('reason'),`${p.reason_code} · ${p.contribution_percent}% rule explanation contribution`);const w=Math.max(850,p.nodes.length*250);g.setAttribute('viewBox',`0 0 ${w} 240`);g.style.minWidth=`${Math.min(w,1100)}px`;const defs=svg('defs',{}),marker=svg('marker',{id:'arrow',viewBox:'0 0 10 10',refX:9,refY:5,markerWidth:6,markerHeight:6,orient:'auto-start-reverse'});marker.append(svg('path',{d:'M 0 0 L 10 5 L 0 10 z',fill:'#587263'}));defs.append(marker);g.append(defs);const gap=w/p.nodes.length; p.relationships.forEach((id,i)=>{const edge=e.highlight_graph.relationships.find(x=>x.id===id),forward=edge.source===p.nodes[i],x1=gap*(i+.5)+92,x2=gap*(i+1.5)-92;g.append(svg('line',{x1:forward?x1:x2,y1:115,x2:forward?x2:x1,y2:115,stroke:'#587263','stroke-width':2,'marker-end':'url(#arrow)'}));g.append(svg('text',{x:(x1+x2)/2,y:82,'text-anchor':'middle','font-size':11,fill:'#587263'},edge.type));edge.provenance.forEach(s=>row($('provenance'),[edge.type,s.source_file,s.source_id,s.source_fields.join(', ')]))});p.nodes.forEach((id,i)=>{const x=gap*(i+.5),parts=id.split(':');g.append(svg('rect',{x:x-92,y:93,width:184,height:58,rx:10,fill:i===0?'#183129':'#e8eee6'}));g.append(svg('text',{x,y:115,'text-anchor':'middle','font-size':12,fill:i===0?'white':'#183129'},parts[0]));g.append(svg('text',{x,y:135,'text-anchor':'middle','font-size':13,'font-weight':600,fill:i===0?'white':'#183129'},parts.slice(1).join(':')))});}
$('request').addEventListener('change',showRequest);$('path').addEventListener('change',showPath);showRequest();
</script></html>'''
    output.write_text(template.replace('__PAYLOAD__', payload))
